/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Complejo;

import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Yoni
 */
public class Interfaz extends javax.swing.JFrame {

    private CaidaRapida complejo;

    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null); //Para ubicarlo en el centro de la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneClases = new javax.swing.JScrollPane();
        textoClases = new javax.swing.JTextArea();
        jScrollPaneConfiteria = new javax.swing.JScrollPane();
        textoConfiteria = new javax.swing.JTextArea();
        jScrollPaneEsquiadores = new javax.swing.JScrollPane();
        textoEsquiadores = new javax.swing.JTextArea();
        jScrollPaneMedio2 = new javax.swing.JScrollPane();
        textoMedio2 = new javax.swing.JTextArea();
        jScrollPaneMedio3 = new javax.swing.JScrollPane();
        textoMedio3 = new javax.swing.JTextArea();
        jScrollPaneMedio4 = new javax.swing.JScrollPane();
        textoMedio4 = new javax.swing.JTextArea();
        jScrollPaneMedio1 = new javax.swing.JScrollPane();
        textoMedio1 = new javax.swing.JTextArea();
        jButtonAbrirCerrar = new javax.swing.JButton();
        jButtonEstadistica = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelEsquiadores = new javax.swing.JLabel();
        jLabelConfiteria = new javax.swing.JLabel();
        jLabelClases = new javax.swing.JLabel();
        jLabelMedio1 = new javax.swing.JLabel();
        jLabelMedio2 = new javax.swing.JLabel();
        jLabelMedio3 = new javax.swing.JLabel();
        jLabelMedio4 = new javax.swing.JLabel();
        jButtonAgregarEsquiador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jScrollPaneClases.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());

        textoClases.setEditable(false);
        textoClases.setColumns(20);
        textoClases.setLineWrap(true);
        textoClases.setRows(5);
        textoClases.setWrapStyleWord(true);
        jScrollPaneClases.setViewportView(textoClases);

        jScrollPaneConfiteria.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPaneConfiteria.setAutoscrolls(true);

        textoConfiteria.setEditable(false);
        textoConfiteria.setColumns(20);
        textoConfiteria.setLineWrap(true);
        textoConfiteria.setRows(5);
        textoConfiteria.setWrapStyleWord(true);
        textoConfiteria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textoConfiteria.setDragEnabled(true);
        jScrollPaneConfiteria.setViewportView(textoConfiteria);

        jScrollPaneEsquiadores.setBorder(null);
        jScrollPaneEsquiadores.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());

        textoEsquiadores.setEditable(false);
        textoEsquiadores.setColumns(20);
        textoEsquiadores.setLineWrap(true);
        textoEsquiadores.setRows(5);
        textoEsquiadores.setToolTipText("");
        textoEsquiadores.setWrapStyleWord(true);
        jScrollPaneEsquiadores.setViewportView(textoEsquiadores);

        textoMedio2.setEditable(false);
        textoMedio2.setColumns(20);
        textoMedio2.setLineWrap(true);
        textoMedio2.setRows(5);
        textoMedio2.setWrapStyleWord(true);
        jScrollPaneMedio2.setViewportView(textoMedio2);

        textoMedio3.setEditable(false);
        textoMedio3.setColumns(20);
        textoMedio3.setLineWrap(true);
        textoMedio3.setRows(5);
        textoMedio3.setWrapStyleWord(true);
        jScrollPaneMedio3.setViewportView(textoMedio3);

        textoMedio4.setEditable(false);
        textoMedio4.setColumns(20);
        textoMedio4.setLineWrap(true);
        textoMedio4.setRows(5);
        textoMedio4.setWrapStyleWord(true);
        jScrollPaneMedio4.setViewportView(textoMedio4);

        textoMedio1.setEditable(false);
        textoMedio1.setColumns(20);
        textoMedio1.setLineWrap(true);
        textoMedio1.setRows(5);
        textoMedio1.setWrapStyleWord(true);
        jScrollPaneMedio1.setViewportView(textoMedio1);

        jButtonAbrirCerrar.setBackground(Color.red);
        jButtonAbrirCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAbrirCerrar.setText("Abrir Complejo");
        jButtonAbrirCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirCerrarActionPerformed(evt);
            }
        });

        jButtonEstadistica.setText("Ver Estadísticas");
        jButtonEstadistica.setEnabled(false);
        jButtonEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstadisticaActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabelEsquiadores.setText("Entrada al complejo");

        jLabelConfiteria.setText("Confitería");

        jLabelClases.setText("Clases");

        jLabelMedio1.setText("Medio de Elevación 1");

        jLabelMedio2.setText("Medio de Elevación 2");

        jLabelMedio3.setText("Medio de Elevación 3");

        jLabelMedio4.setText("Medio de Elevación 4");

        jButtonAgregarEsquiador.setText("Agregar Esquiador");
        jButtonAgregarEsquiador.setEnabled(false);
        jButtonAgregarEsquiador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarEsquiadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabelEsquiadores)
                                .addGap(146, 146, 146)
                                .addComponent(jLabelConfiteria)
                                .addGap(249, 249, 249)
                                .addComponent(jLabelClases)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMedio1)
                                .addGap(18, 126, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPaneMedio2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMedio2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabelMedio3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jScrollPaneMedio3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPaneMedio4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPaneEsquiadores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPaneConfiteria, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPaneClases, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonEstadistica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonAbrirCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonAgregarEsquiador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPaneMedio1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelMedio4)
                        .addGap(158, 158, 158))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEsquiadores)
                    .addComponent(jLabelConfiteria)
                    .addComponent(jLabelClases))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAbrirCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAgregarEsquiador, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEstadistica, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPaneEsquiadores, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPaneConfiteria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                        .addComponent(jScrollPaneClases)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMedio1)
                    .addComponent(jLabelMedio2)
                    .addComponent(jLabelMedio3)
                    .addComponent(jLabelMedio4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneMedio4)
                    .addComponent(jScrollPaneMedio3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneMedio2)
                    .addComponent(jScrollPaneMedio1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbrirCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirCerrarActionPerformed

        if (jButtonAbrirCerrar.getBackground() == Color.red) {
            jButtonAbrirCerrar.setBackground(Color.GREEN);
            jButtonAbrirCerrar.setForeground(Color.BLACK);
            jButtonAbrirCerrar.setText("Cerrar Complejo");
            jButtonAgregarEsquiador.setEnabled(true);
            this.complejo = new CaidaRapida(textoConfiteria, textoClases, textoEsquiadores, textoMedio1, textoMedio2, textoMedio3, textoMedio4, this);
            complejo.iniciaMedios(complejo);
            complejo.abrirComplejo();
            Random r = new Random();
            int aux;
            try {
                for (aux = 0; aux < 50; aux++) {
                    String nombre = "E" + aux;
                    complejo.entraEsquiador(complejo, nombre);
                    Thread.sleep(r.nextInt(100));
                }
            } catch (InterruptedException ex) {
                System.err.println("Error en Boton Abrir Complejo.");
            }
        } else {
            jButtonAbrirCerrar.setBackground(Color.RED);
            jButtonAbrirCerrar.setText("Complejo Cerrado");
            jButtonAbrirCerrar.setForeground(Color.WHITE);
            jButtonAbrirCerrar.setEnabled(false);
            jButtonAgregarEsquiador.setEnabled(false);
            complejo.cerrarComplejo();
        }

    }//GEN-LAST:event_jButtonAbrirCerrarActionPerformed
    public void habilitarEstadística() {
        jButtonEstadistica.setEnabled(true);
    }

    public void cerroComplejo() {
        jButtonAbrirCerrar.setBackground(Color.RED);
        jButtonAbrirCerrar.setText("Complejo Cerrado");
        jButtonAbrirCerrar.setForeground(Color.WHITE);
        jButtonAbrirCerrar.setEnabled(false);
        jButtonAgregarEsquiador.setEnabled(false);
    }

    private void jButtonEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstadisticaActionPerformed
        JOptionPane.showMessageDialog(rootPane, complejo.getEstadistica());
    }//GEN-LAST:event_jButtonEstadisticaActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAgregarEsquiadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarEsquiadorActionPerformed
        String nombre = JOptionPane.showInputDialog("Escribe el nombre del esquiador:");
        complejo.entraEsquiador(complejo, nombre);
    }//GEN-LAST:event_jButtonAgregarEsquiadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrirCerrar;
    private javax.swing.JButton jButtonAgregarEsquiador;
    private javax.swing.JButton jButtonEstadistica;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelClases;
    private javax.swing.JLabel jLabelConfiteria;
    private javax.swing.JLabel jLabelEsquiadores;
    private javax.swing.JLabel jLabelMedio1;
    private javax.swing.JLabel jLabelMedio2;
    private javax.swing.JLabel jLabelMedio3;
    private javax.swing.JLabel jLabelMedio4;
    private javax.swing.JScrollPane jScrollPaneClases;
    private javax.swing.JScrollPane jScrollPaneConfiteria;
    private javax.swing.JScrollPane jScrollPaneEsquiadores;
    private javax.swing.JScrollPane jScrollPaneMedio1;
    private javax.swing.JScrollPane jScrollPaneMedio2;
    private javax.swing.JScrollPane jScrollPaneMedio3;
    private javax.swing.JScrollPane jScrollPaneMedio4;
    private javax.swing.JTextArea textoClases;
    private javax.swing.JTextArea textoConfiteria;
    private javax.swing.JTextArea textoEsquiadores;
    private javax.swing.JTextArea textoMedio1;
    private javax.swing.JTextArea textoMedio2;
    private javax.swing.JTextArea textoMedio3;
    private javax.swing.JTextArea textoMedio4;
    // End of variables declaration//GEN-END:variables
}
